/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.transaksi;

import DB.Barang;
import DB.BarangKeluar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import tools.Converter;
import tools.Session;
import views.login.Login;

/**
 *
 * @author ASUS
 */
public class InsertKeluar extends javax.swing.JFrame {

    /**
     * Creates new form InsertKeluar
     */
    public InsertKeluar() {
        initComponents();
        // set icon
        ImageIcon icon = new ImageIcon(Login.class.getResource("/assets/images/icon.png"));
        setIconImage(icon.getImage());
        setItemList(barangModels.getList());
    }

    private void setItemList(Object[][] data) {
        for (int i = 0; i < data.length; i++) {
            listBarang.addItem((String) data[i][1]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listBarang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        inputTgl = new com.toedter.calendar.JDateChooser();
        btnKeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nama Barang");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jPanel1.add(listBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 191, -1));

        jLabel2.setText("Jumlah Barang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 191, -1));
        jPanel1.add(inputTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 100, 190, -1));

        btnKeluar.setText("Transaksi Barang");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 281, -1));

        jLabel3.setText("Tanggal Masuk");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 340, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        if ((int) jSpinner1.getValue() == 0 || inputTgl == null) {
            JOptionPane.showMessageDialog(null, "Isi data terlebih dahulu", "Pesan", JOptionPane.WARNING_MESSAGE);
        } else {
            String nama = listBarang.getSelectedItem().toString();
            int jumlahBarang = (int) jSpinner1.getValue();
            int idPetugas = Session.getId();
            String tgl = Converter.formatTanggal(inputTgl.getDate());
            int idBarang = barangModels.getIdBarang(nama);
            if(barangKeluarModels.insert(idBarang, tgl, jumlahBarang, idPetugas)){
                JOptionPane.showMessageDialog(null, "Berhasil", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Jumlah barang yang diinput melebihi stok digudang", "Warning", JOptionPane.WARNING_MESSAGE);
            };
            
        }

    }//GEN-LAST:event_btnKeluarActionPerformed


    private BarangKeluar barangKeluarModels = new BarangKeluar("barang_keluar");
    private Barang barangModels = new Barang("barang");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private com.toedter.calendar.JDateChooser inputTgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> listBarang;
    // End of variables declaration//GEN-END:variables
}
