/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.transaksi;

import DB.Barang;
import DB.Supplier;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import tools.Converter;
import tools.Session;
import views.dashboard.Dashboard;
import views.login.Login;

/**
 *
 * @author ASUS
 */
public class InsertMasuk extends javax.swing.JFrame {

    /**
     * Creates new form BarangMasuk
     */
    public InsertMasuk() {
        initComponents();
        setLocationRelativeTo(null);
        // set icon
        ImageIcon icon = new ImageIcon(Login.class.getResource("/assets/images/icon.png"));
        setIconImage(icon.getImage());
        addList();
    }

    private void addList() {
        Object[][] datas = barang.getList();
        for (int i = 0; i < datas.length; i++) {
            listBarang.addItem((String) datas[i][1]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listBarang = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMasuk = new javax.swing.JButton();
        inputTgl = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.add(listBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 190, -1));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 190, -1));

        jLabel1.setText("Nama Barang");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Jumlah Barang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btnMasuk.setText("Transaksi Barang");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        jPanel1.add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 280, -1));
        jPanel1.add(inputTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 190, -1));

        jLabel3.setText("Tanggal Masuk");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
        if ((int) jSpinner1.getValue() == 0 || inputTgl.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Isi data terlebih dahulu", "Pesan", JOptionPane.WARNING_MESSAGE);
        } else {
            String nama = listBarang.getSelectedItem().toString();
            int jumlah = (int) jSpinner1.getValue();
            String tanggal = Converter.formatTanggal(inputTgl.getDate());
            int idBarang = barang.getIdBarang(nama);
            int idSupp = barang.getIdSupplier(idBarang);
            barangMasuk.insert(idBarang, tanggal, jumlah, idSupp, this.idPetugas);
            JOptionPane.showMessageDialog(null, "Berhasil", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnMasukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertMasuk().setVisible(true);
            }
        });
    }

    private DB.BarangMasuk barangMasuk = new DB.BarangMasuk("barang_masuk");
    private Barang barang = new Barang("barang");
    private Supplier supplierModel = new Supplier("supplier");
    private int idPetugas = Session.getId();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMasuk;
    private com.toedter.calendar.JDateChooser inputTgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> listBarang;
    // End of variables declaration//GEN-END:variables
}
