/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.transaksi;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import tools.Converter;
import views.login.Login;

/**
 *
 * @author ASUS
 */
public class TransaksiMasuk extends javax.swing.JFrame {

    /**
     * Creates new form BarangMasuk
     */
    public TransaksiMasuk() {
        initComponents();
        
        // set icon
        ImageIcon icon = new ImageIcon(Login.class.getResource("/assets/images/icon.png"));
        setIconImage(icon.getImage());
        
        setLocationRelativeTo(null);
        setTabel();
    }

    private void setTabel() {
        tabelMasuk.setModel(new DefaultTableModel(barangMasukModel.selectAll(), listTable));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMasuk = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        tglAwal = new com.toedter.calendar.JDateChooser();
        tglAkhir = new com.toedter.calendar.JDateChooser();
        filterData = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(83, 113, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelMasuk);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 89, 830, 410));

        btnTambah.setText("Tambah Data Barang Masuk");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 190, -1));
        jPanel1.add(tglAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 185, -1));
        jPanel1.add(tglAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 184, -1));

        filterData.setText("Filter");
        filterData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterDataActionPerformed(evt);
            }
        });
        jPanel1.add(filterData, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 122, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 129, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftar Barang Masuk");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        new InsertMasuk().setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void filterDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDataActionPerformed
        // TODO add your handling code here:
        try {
            if (tglAwal == null || tglAkhir == null) {
            setTabel();
        } else {
            String awal = Converter.formatTanggal(tglAwal.getDate());
            String akhir = Converter.formatTanggal(tglAkhir.getDate());
            Object[][] data = Converter.convertArray(barangMasukModel.filter(awal, akhir));
            tabelMasuk.setModel(new DefaultTableModel(data, listTable));
        }
        } catch (Exception e) {
            setTabel();
        }
    }//GEN-LAST:event_filterDataActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        setTabel();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private DB.BarangMasuk barangMasukModel = new DB.BarangMasuk("barang_masuk");
    private String[] listTable = {"ID Transaksi", "Tanggal Masuk", "Jumlah", "Nama Barang", "Supplier", "Nama Petugas"};
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton filterData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelMasuk;
    private com.toedter.calendar.JDateChooser tglAkhir;
    private com.toedter.calendar.JDateChooser tglAwal;
    // End of variables declaration//GEN-END:variables
}
