/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.dashboard;

import views.login.Login;
import DB.*;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import tools.Session;
import tools.Converter;
import view.tambahBarang.TambahBarang;

/**
 *
 * @author ASUS
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form NewFrame
     */
    public Dashboard() {
        initComponents();
        setLocationRelativeTo(null);
        setLabelTotal();
        // set icon
        ImageIcon icon = new ImageIcon(Login.class.getResource("/assets/images/icon.png"));
        setIconImage(icon.getImage());

//        JOptionPane.showMessageDialog(null, "Hallo " + nama, "Selamat Datang", JOptionPane.PLAIN_MESSAGE);
        labelNama.setText(nama);
        labelRole.setText(role);
        btnHapus.setVisible(false);
        tampilanPetugas.setVisible(false);
        
        
        jTable1.setModel(new DefaultTableModel(petugasModel.getAllData(), list));
    }
    
    private void setLabelTotal(){
        totalBarang.setText("" + barang.getTotalData());
        totalBarangMasuk.setText("" + barangMasuk.getTotalData());
        totalBarangKeluar.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        panelUser = new javax.swing.JPanel();
        labelRole = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        petugasKlik = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        barangKlik = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        tampilanBarang = new javax.swing.JPanel();
        panelBarang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalBarang = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        panelBarang2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        totalBarangMasuk = new javax.swing.JLabel();
        panelBarang1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalBarangKeluar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        findBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        btnBarangMasuk = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        tampilanPetugas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(83, 113, 136));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 670));

        panelUser.setBackground(new java.awt.Color(83, 113, 136));
        panelUser.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true), "D A S H B O A R D", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS PGothic", 2, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panelUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRole.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        labelRole.setForeground(new java.awt.Color(255, 255, 255));
        labelRole.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRole.setText("role");
        panelUser.add(labelRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, -1));

        labelNama.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNama.setText("nama");
        panelUser.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 230, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/home.png"))); // NOI18N
        panelUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 270, 390));

        petugasKlik.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        petugasKlik.setForeground(new java.awt.Color(255, 255, 255));
        petugasKlik.setText("Daftar Petugas");
        petugasKlik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petugasKlikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                petugasKlikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                petugasKlikMouseExited(evt);
            }
        });
        panelUser.add(petugasKlik, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jToolBar1.setRollover(true);
        panelUser.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 270, 4));

        barangKlik.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        barangKlik.setForeground(new java.awt.Color(255, 255, 255));
        barangKlik.setText("Warehouse");
        barangKlik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barangKlikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barangKlikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barangKlikMouseExited(evt);
            }
        });
        panelUser.add(barangKlik, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        getContentPane().add(panelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 650));

        jPanel4.setBackground(new java.awt.Color(83, 113, 136));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, 670));

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1010, 670));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tampilanBarang.setBackground(new java.awt.Color(83, 113, 136));
        tampilanBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarang.setBackground(new java.awt.Color(51, 47, 208));
        panelBarang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Barang");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelBarang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        totalBarang.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        totalBarang.setForeground(new java.awt.Color(255, 255, 255));
        totalBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBarang.setText("0");
        panelBarang.add(totalBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, -1));

        tampilanBarang.add(panelBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 210, 80));

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            barang.getDataBarang(),
            listBarang
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        tampilanBarang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 950, 380));

        panelBarang2.setBackground(new java.awt.Color(84, 180, 53));
        panelBarang2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBarang2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Transaksi Barang Masuk");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelBarang2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        totalBarangMasuk.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        totalBarangMasuk.setForeground(new java.awt.Color(255, 255, 255));
        totalBarangMasuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBarangMasuk.setText("0");
        panelBarang2.add(totalBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, -1));

        tampilanBarang.add(panelBarang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 210, 80));

        panelBarang1.setBackground(new java.awt.Color(237, 43, 42));
        panelBarang1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelBarang1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Transaksi Barang Keluar");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelBarang1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        totalBarangKeluar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        totalBarangKeluar.setForeground(new java.awt.Color(255, 255, 255));
        totalBarangKeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBarangKeluar.setText("0");
        panelBarang1.add(totalBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 210, -1));

        tampilanBarang.add(panelBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, 80));

        jButton1.setText("Tambah Barang Baru");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        tampilanBarang.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 160, 30));

        findBarang.setText("Cari barang berdasarkan nama");
        findBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                findBarangKeyTyped(evt);
            }
        });
        tampilanBarang.add(findBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 260, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/inventory-icon-vector-11.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tampilanBarang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, 80));

        btnHapus.setText("Hapus Barang");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        tampilanBarang.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 140, 30));

        btnHapus1.setText("Hapus Barang");
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });
        tampilanBarang.add(btnHapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 140, 30));

        btnBarangMasuk.setText("Barang Masuk");
        btnBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarangMasukActionPerformed(evt);
            }
        });
        tampilanBarang.add(btnBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 110, 30));

        jButton3.setText("Barang Keluar");
        tampilanBarang.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 110, 30));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        tampilanBarang.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 620, 120, -1));

        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        tampilanBarang.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, 30));

        jLayeredPane1.add(tampilanBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 670));

        tampilanPetugas.setBackground(new java.awt.Color(83, 113, 136));
        tampilanPetugas.setPreferredSize(new java.awt.Dimension(1010, 670));
        tampilanPetugas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        tampilanPetugas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 840, 400));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Daftar Petugas");
        jLabel6.setOpaque(true);
        tampilanPetugas.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 230, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/6345962.png"))); // NOI18N
        tampilanPetugas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jButton2.setText("Tambah");
        tampilanPetugas.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 120, -1));

        jButton4.setText("Hapus");
        tampilanPetugas.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 120, -1));

        btnLogout1.setText("Logout");
        btnLogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogout1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogout1MouseExited(evt);
            }
        });
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        tampilanPetugas.add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, 30));

        jLayeredPane1.add(tampilanPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 670));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1030, 670));

        jPanel6.setBackground(new java.awt.Color(83, 113, 136));
        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, -1));

        jPanel7.setBackground(new java.awt.Color(83, 113, 136));
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new TambahBarang().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        int nomor = tabelBarang.getSelectedRow();
        this.idBarang = Integer.parseInt(tabelBarang.getValueAt(nomor, 0).toString());
        btnHapus.setVisible(true);
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void findBarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findBarangKeyTyped
        // TODO add your handling code here:
        String findName = findBarang.getText();
        Object[][] datas = Converter.convertArray(barang.findBarangByName(findName));
        tabelBarang.setModel(new DefaultTableModel(datas, listBarang));
    }//GEN-LAST:event_findBarangKeyTyped

    public void refresh(){
        totalBarang.setText("" + barang.getTotalData());
        tabelBarang.setModel(new DefaultTableModel(barang.getDataBarang(), listBarang));
    }
    
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data?", "WARNING", JOptionPane.WARNING_MESSAGE);
        if (option == JOptionPane.OK_OPTION) {
            barang.deleteBarang(idBarang);
            JOptionPane.showMessageDialog(null, "Berhasil menghapus data barang", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            refresh();
        } else {
            refresh();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void btnBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarangMasukActionPerformed
        // TODO add your handling code here:
        new views.transaksi.BarangMasuk().setVisible(true);
    }//GEN-LAST:event_btnBarangMasukActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btnRefreshActionPerformed
    

    
    private void petugasKlikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasKlikMouseClicked
        // TODO add your handling code here:
        if (role.equalsIgnoreCase("petugas")) {
            JOptionPane.showMessageDialog(null, "Maaf Anda Tidak Dapat Mengakses Ini", "Pesan", JOptionPane.WARNING_MESSAGE);
            tampilanPetugas.setVisible(false);
            tampilanBarang.setVisible(true);
        }else{
            tampilanPetugas.setVisible(true);
            tampilanBarang.setVisible(false);
        }
            
    }//GEN-LAST:event_petugasKlikMouseClicked

    private void barangKlikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangKlikMouseClicked
        // TODO add your handling code here:
        tampilanPetugas.setVisible(false);
        tampilanBarang.setVisible(true);
    }//GEN-LAST:event_barangKlikMouseClicked

    private void petugasKlikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasKlikMouseEntered
        // TODO add your handling code here:
        petugasKlik.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_petugasKlikMouseEntered

    private void petugasKlikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petugasKlikMouseExited
        // TODO add your handling code here:
        petugasKlik.setForeground(Color.WHITE);
    }//GEN-LAST:event_petugasKlikMouseExited

    private void barangKlikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangKlikMouseEntered
        // TODO add your handling code here:
        barangKlik.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_barangKlikMouseEntered

    private void barangKlikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangKlikMouseExited
        // TODO add your handling code here:
        barangKlik.setForeground(Color.WHITE);
    }//GEN-LAST:event_barangKlikMouseExited

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnLogout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogout1MouseClicked

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setForeground(Color.white);
        btnLogout.setBackground(Color.red);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setForeground(Color.black);
        btnLogout.setBackground(Color.white);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnLogout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout1MouseEntered
        // TODO add your handling code here:
        btnLogout1.setForeground(Color.white);
        btnLogout1.setBackground(Color.red);
    }//GEN-LAST:event_btnLogout1MouseEntered

    private void btnLogout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogout1MouseExited
        // TODO add your handling code here:
        btnLogout1.setForeground(Color.black);
        btnLogout1.setBackground(Color.white);
    }//GEN-LAST:event_btnLogout1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    private int idBarang = 0;
    private String nama = Session.getName();
    private String role = Session.getRole();
//    private String role = "Admin";
    private Barang barang = new Barang("barang");
    private BarangMasuk barangMasuk = new BarangMasuk("barang_masuk");
    private BarangKeluar barangKeluar = new BarangKeluar("barang_keluar");
    private String[] listBarang = {"ID Barang", "Nama Barang", "Jumlah", "Nama Supplier"};
    
    //Deklarasi Petugas
    private Petugas petugasModel = new Petugas("petugas");
    private String[] list = {"ID", "Nama", "Jenis Kelamin", "Email", "Username", "Role"};
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barangKlik;
    private javax.swing.JButton btnBarangMasuk;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JTextField findBarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelRole;
    private javax.swing.JPanel panelBarang;
    private javax.swing.JPanel panelBarang1;
    private javax.swing.JPanel panelBarang2;
    private javax.swing.JPanel panelUser;
    private javax.swing.JLabel petugasKlik;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JPanel tampilanBarang;
    private javax.swing.JPanel tampilanPetugas;
    private javax.swing.JLabel totalBarang;
    private javax.swing.JLabel totalBarangKeluar;
    private javax.swing.JLabel totalBarangMasuk;
    // End of variables declaration//GEN-END:variables
}
