/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.*;
import javax.swing.*;
import session.Session;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        gambar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        labelForgot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUtama.setBackground(new java.awt.Color(83, 113, 136));
        panelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/images/home.png"))); // NOI18N
        panelUtama.add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MyGudang");
        panelUtama.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 220, 50));

        usernameText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        usernameText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        panelUtama.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 280, -1));

        passwordText.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        passwordText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        panelUtama.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 280, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        panelUtama.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Selamat datang, silahkan login");
        panelUtama.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        panelUtama.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelUtama.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 280, -1));

        labelForgot.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        labelForgot.setForeground(new java.awt.Color(255, 255, 255));
        labelForgot.setText("Lupa password anda?");
        labelForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelForgotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelForgotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelForgotMouseExited(evt);
            }
        });
        panelUtama.add(labelForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        getContentPane().add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelForgotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelForgotMouseEntered
        // TODO add your handling code here:
        labelForgot.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_labelForgotMouseEntered

    private void labelForgotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelForgotMouseExited
        // TODO add your handling code here:
        labelForgot.setForeground(Color.WHITE);
    }//GEN-LAST:event_labelForgotMouseExited

    private void labelForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelForgotMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Silahkan hubungi administrator", "Pesan", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_labelForgotMouseClicked

    private boolean checkPassword(char[] password) {
        String data = new String(password);
        boolean hasil = data.matches("[a-zA-Z0-9]+");
        if (hasil) {
            return false;
        } else {
            return true;
        }
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = usernameText.getText();
        char[] password = passwordText.getPassword();
        if (checkPassword(password)) {
            JOptionPane.showMessageDialog(rootPane, "Terdapat Karakter Khusus", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if(username.equals("admin") && new String(password).equals("admin")) {
            JOptionPane.showMessageDialog(rootPane, "Aman", "Aman", JOptionPane.INFORMATION_MESSAGE);
            Session.setRole("Petugas");
            new NewFrame().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Username dan Password anda salah", "Gagal", JOptionPane.ERROR_MESSAGE);        
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelForgot;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
