/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.barang;

import DB.Barang;
import java.util.Arrays;

/**
 *
 * @author ASUS
 */
public class EditBarang extends javax.swing.JFrame {

    /**
     * Creates new form TambahBarang
     */
    public EditBarang() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public EditBarang(int id) {
        initComponents();
        setLocationRelativeTo(null);
        data = barang.getDataBarangById(id);
        idTxt.setText("" + data[0]);
        namaTxt.setText("" + data[1]);
        jumlahTxt.setText("" + data[2]);
        idSuppTxt.setText("" + data[3]);
//        System.out.println(Arrays.deepToString(data));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namaTxt = new javax.swing.JTextField();
        jumlahTxt = new javax.swing.JTextField();
        idSuppTxt = new javax.swing.JTextField();
        idTxt = new javax.swing.JTextField();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaTxt.setText("jTextField1");
        jPanel1.add(namaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, -1));

        jumlahTxt.setText("jTextField2");
        jPanel1.add(jumlahTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 110, -1));

        idSuppTxt.setText("jTextField3");
        jPanel1.add(idSuppTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 110, -1));

        idTxt.setText("jTextField1");
        jPanel1.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBarang().setVisible(true);
            }
        });
    }
    private Object[] data = null;
    private Barang barang = new Barang("barang");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idSuppTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlahTxt;
    private javax.swing.JTextField namaTxt;
    // End of variables declaration//GEN-END:variables
}
